SET DEFINE OFF

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (1, 1000, to_date('03-Jan-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (2, 5000, to_date('06-Jan-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (3, 1000, to_date('08-Jan-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (4, 1000, to_date('13-Jan-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (5, 2000, to_date('03-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (6, 1750, to_date('03-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (7, 1500, to_date('05-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (8, 250, to_date('11-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (9, 250, to_date('11-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (10, 500, to_date('13-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.INVOICE (PO_ID, GROSS_AMT, CREATED_DATE) 
VALUES (11, 800, to_date('16-Feb-23', 'DD-MON-RR'));

commit;
