SET DEFINE OFF

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (1, 1, to_date('03-Jan-23', 'DD-MON-RR'), 'PAID', 1000, to_date('03-Jan-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (2, 5, to_date('06-Jan-23', 'DD-MON-RR'), 'PAID', 5000, to_date('06-Jan-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (3, 1, to_date('08-Jan-23', 'DD-MON-RR'), 'PAID', 1000, to_date('08-Jan-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (4, 1, to_date('13-Jan-23', 'DD-MON-RR'), 'PAID', 4000, to_date('25-Jan-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (5, 2, to_date('03-Feb-23', 'DD-MON-RR'), 'PAID', 2000, to_date('03-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (6, 1, to_date('03-Feb-23', 'DD-MON-RR'), 'PAID', 1750, to_date('03-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (7, 3, to_date('05-Feb-23', 'DD-MON-RR'), 'PAID', 1500, to_date('05-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (8, 4, to_date('11-Feb-23', 'DD-MON-RR'), 'PAID', 250, to_date('11-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (9, 5, to_date('11-Feb-23', 'DD-MON-RR'), 'PAID', 250, to_date('11-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (10, 5, to_date('13-Feb-23', 'DD-MON-RR'), 'PAID', 500, to_date('13-Feb-23', 'DD-MON-RR'));

INSERT INTO ADMIN.VOUCHER (INVOICE_ID, VENDOR_ID, INVOICE_DATE, STATUS, GROSS_AMT, ACCOUNTING_DATE) 
VALUES (11, 5, to_date('16-Feb-23', 'DD-MON-RR'), 'PAID', 800, to_date('25-Feb-23', 'DD-MON-RR'));

commit;
